---
kind: Service
apiVersion: v1
metadata:
  name: vue-todo-service
spec:
  selector:
    app: vue-todo
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 80
      nodePort: 30001
  type: LoadBalancer


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vue-todo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: vue-todo
    spec:
      containers:
        - name: vue-todo
          image: alisawari/vue-todo
          ports:
          - containerPort: 3000
